version: 0.2

phases:
  pre_build:
    commands:
      - pip install pillow

  build:
    commands:
      - python -m unittest discover -s schoolmanagement
artifacts:
  files:
    - '**/*'
  base-directory: schoolmanagement